const countryName = [
  'Afghanistan','Albania','Algeria','Andorra','Angola','Antigua and Barbuda','Argentina','Armenia','Australia','Austria','Azerbaijan','Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium','Belize','Benin','Bhutan','Bolivia','Bosnia and Herzegovina','Botswana','Brazil','Brunei','Bulgaria','Burkina Faso','Burundi','Cabo Verde','Cambodia','Cameroon','Canada','Central African Republic','Chad','Chile','China','Colombia','Comoros','Congo','Costa Rica','Croatia','Cuba','Cyprus','Czechia','Democratic Republic of the Congo','Denmark','Djibouti','Dominica','Dominican Republic','Ecuador','Egypt','El Salvador','Equatorial Guinea','Eritrea','Estonia','Eswatini','Ethiopia','Fiji','Finland','France','Gabon','Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala','Guinea','Guinea-Bissau','Guyana','Haiti','Holy See','Honduras','Hungary','Iceland','India','Indonesia','Iran','Iraq','Ireland','Israel','Italy','Jamaica','Japan','Jordan','Kazakhstan','Kenya','Kiribati','Kuwait','Kyrgyzstan','Laos','Latvia','Lebanon','Lesotho','Liberia','Libya','Liechtenstein','Lithuania','Luxembourg','Madagascar','Malawi','Malaysia','Maldives','Mali','Malta','Marshall Islands','Mauritania','Mauritius','Mexico','Micronesia','Moldova','Monaco','Mongolia','Montenegro','Morocco','Mozambique','Myanmar','Namibia','Nauru','Nepal','Netherlands','New Zealand','Nicaragua','Niger','Nigeria','North Korea','North Macedonia','Norway','Oman','Pakistan','Palau','Palestine State','Panama','Papua New Guinea','Paraguay','Peru','Philippines','Poland','Portugal','Qatar','Romania','Russia','Rwanda','Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Samoa','San Marino','Sao Tome and Principe','Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone','Singapore','Slovakia','Slovenia','Solomon Islands','Somalia','South Africa','South Korea','South Sudan','Spain','Sri Lanka','Sudan','Suriname','Sweden','Switzerland','Syria','Tajikistan','Tanzania','Thailand','Timor-Leste','Togo','Tonga','Trinidad and Tobago','Tunisia','Turkey','Turkmenistan','Tuvalu','Uganda','Ukraine','United Arab Emirates','United Kingdom','United States of America','Uruguay','Uzbekistan','Vanuatu','Venezuela','Vietnam','Yemen','Zambia','Zimbabwe'
]

const cityName = [
  'Tokyo','Delhi','Shanghai','Sao Paulo','Mexico City','Dhaka','Cairo','Beijing','Mumbai','Osaka','Karachi','Chongqing','Istanbul','Buenos Aires','Kolkata','Lagos','Kinshasa','Manila','Tianjin','Rio De Janeiro','Guangzhou','Lahore','Moscow','Shenzhen','Bangalore','Paris','Bogota','Chennai','Jakarta','Lima','Bangkok','Hyderabad','Seoul','Nagoya','London','Chengdu','Tehran','Nanjing','Wuhan','Luanda','New York','Ahmedabad','Xian','Kuala Lumpur','Hangzhou','Hong Kong','Dongguan','Foshan','Riyadh','Shenyang','Surat','Baghdad','Suzhou Jiangsu','Santiago','Dar Es Salaam','Pune','Madrid','Harbin','Toronto','Belo Horizonte','Singapore','Khartoum','Johannesburg','Qingdao','Dalian','Barcelona','Fukuoka','St Petersburg','Jinan','Yangon','Zhengzhou','Alexandria','Abidjan','Guadalajara','Ankara','Chittagong','Melbourne','Sydney','Monterrey','Addis Ababa','Nairobi','Brasilia','Cape Town','Jiddah','Changsha','Kunming','Changchun','Xinbei','Urumqi','Shantou','Rome','Hefei','Kabul','Montreal','Tel Aviv','Porto Alegre','Recife','Ningbo','Shijiazhuang','Fortaleza','Los Angeles','Medellin','Kano','Yaounde','Jaipur','Ekurhuleni','Taiyuan Shanxi','Nanning','San Salvador','Casablanca','Xiamen','Fuzhou Fujian','Curitiba','Lucknow','Douala','Changzhou','Wenzhou','Nanchang','Berlin','Kozhikode','Ibadan','Busan','Faisalabad','Tangshan Hebei','Bekasi','Malappuram','Antananarivo','Kumasi','Asuncion','Santo Domingo','Guiyang','Campinas','Kampala','Abuja','Wuxi Jiangsu','Mashhad','Puebla','Durban','Athens','Dakar','Milan','Kanpur','Kuwait City','Pyongyang','Kochi','Lanzhou','Thrissur','Port Harcourt','Indore','Guayaquil','Kiev','Sanaa','Lisbon','Surabaya','Caracas','Guatemala City','Shizuoka','Zhongshan','Nagpur','Dubai','Incheon','Coimbatore','Cali','Ouagadougou','Lusaka','Port Au Prince','Algiers','Manchester','Depok','Taiyuan','Chicago','Goiania','Sapporo','Huaian','Weifang','Zibo','Bamako','Thiruvananthapuram','Vancouver','Bandung','Pretoria','Shaoxing','Yantai','Mbuji Mayi','Huizhou','Tashkent','Accra','Lubumbashi','Toluca De Lerdo','San Juan','Patna','Beirut','Brisbane','Damascus','Bhopal','Brazzaville','Luoyang','Tunis','Baku','Houston'
];

module.exports = countryName;
module.exports = cityName;